web:
  image: tmp:nginx
  container_name: nginx
  ports:
    - 80:80
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
    - ./data/:/var/www/host.example/
  links:
    - fpm
fpm:
  image: tmp:fpm
  container_name: fpm
  volumes:
    - ./fpm/www.conf:/etc/opt/remi/php74/php-fpm.d/www.conf 
    - ./data/:/var/www/host.example/
