version: '3.7'
services:
  front:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
      - ./nginx/ssl:/etc/nginx/ssl/
      - ./data/:/var/www/proxy.admux.ru/
    links:
      - back
  back:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    container_name: fpm
    volumes:
      - ./fpm/www.conf:/etc/opt/remi/php74/php-fpm.d/www.conf 
      - ./data/:/var/www/proxy.admux.ru/
